package:
    name: click-plugins
    version: "1.0.3"

source:
    fn: click-plugins-1.0.3.tar.gz
    url: https://pypi.python.org/packages/source/c/click-plugins/click-plugins-1.0.3.tar.gz
    md5: ddc85a5c51399713f801ae6b63fcac5b

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - click >=3.0
    run:
        - python
        - click >=3.0

test:
    imports:
        - click_plugins

about:
    home: https://github.com/click-contrib/click-plugins
    license: BSD License
    summary: 'An extension module for click to enable registering CLI commands via setuptools entry-points.'
