package:
    name: icclim
    version: 4.2.9n

source:
    git_url: https://github.com/NESII/icclim.git
#    git_url: https://github.com/cerfacs-globc/icclim
    git_tag: i-py3-imports
#    git_tag: 4.2.9

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - numpy
        - netcdf4
        - gcc

    run:
        - python
        - numpy
        - netcdf4
        - libgcc

test:
    imports:
        - icclim

about:
    home: http://icclim.readthedocs.org/en/latest/
    license: Apache 2.0 License
    summary: Index Calculation CLIMate (ICCLIM) is a Python library for climate indices calculation.
