package:
    name: icclim
    version: {{ environ['CONDA_ICCLIM_VER'] }}

source:
    git_url: {{ environ['CONDA_ICCLIM_REP'] }}
    git_tag: {{ environ['CONDA_ICCLIM_VER'] }}

build:
    number: {{ environ['CONDA_ICCLIM_BNO'] }}

requirements:
    build:
        - python
        - setuptools
        - numpy
        - netcdf4
        - gcc

    run:
        - python
        - numpy
        - netcdf4
        - libgcc

test:
    imports:
        - icclim

about:
    home: http://icclim.readthedocs.org/en/latest/
    license: Apache 2.0 License
    summary: Index Calculation CLIMate (ICCLIM) is a Python library for climate indices calculation.
