package:
    name: udunits2
    version: 2.2.20

source:
    fn: v2.2.20.tar.gz
    url: https://github.com/Unidata/UDUNITS-2/archive/v2.2.20.tar.gz
    sha1: a0d30024af16749a4a5ca60133b32735ae52f9e2

build:
    number: 0
    detect_binary_files_with_prefix: true

test:
    commands:
        - udunits2 -h
        - udunits2 -H meter -W miles

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: https://github.com/Unidata/UDUNITS-2/blob/master/COPYRIGHT
  summary: The UDUNITS package supports units of physical quantities.