package:
    name: ocgis
    version: 1.3.0.dev1

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: next

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - numpy
        - netcdf4
        - shapely
        - fiona
        - gdal <2
        - proj.4
    run:
        - python
        - numpy
        - netcdf4
        - shapely
        - fiona
        - gdal <2
        - cf_units
        - rtree
        - proj.4

test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.