package:
    name: ocgis
    version: 1.3.0.dev1

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: master

build:
    number: 0
    skip: True # [win]
    skip: True # [py3k]

requirements:
    build:
        - python >=2.7,<3
        - fiona ==1.6.3
        - netcdf4
        - numpy
        - shapely
        - rtree
        - cf_units
        - icclim ==4.1.1
    run:
        - python
        - fiona ==1.6.3
        - netcdf4
        - numpy
        - shapely
        - proj.4
        - rtree
        - cf_units
        - krb5
        - icclim ==4.1.1
#        - esmpy==7.0.0  #Optional!

test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.
