package:
    name: ocgis
    version: 1.2.1

source:
#    git_url: https://github.com/NCPP/ocgis.git
#    git_tag: v1.2.1
    # tdk: rever to tag when tagged
    path: /ocgis

build:
    number: 0
    skip: True # [win]
    skip: True # [osx]
    skip: True # [py3k]

requirements:
    build:
        - python >=2.7,<3
        - cfunits-python
        - fiona ==1.6.3
        - netcdf4
        - numpy
        - shapely
        - cfunits-python
        - rtree
    run:
        - python
        - cfunits-python
        - fiona ==1.6.3
        - netcdf4
        - numpy
        - shapely
        - rtree
        - krb5

test:
  requires:
    - nose

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.