package:
    name: cf_units
    version: 1.1

source:
    git_url: https://github.com/SciTools/cf_units.git
    git_tag: v1.1

build:
    number: 0

requirements:
    build:
        - python
        - udunits2
    run:
        - python
        - six
        - udunits2
        - netcdf4
        - numpy

test:
    imports:
        - cf_units

about:
    home: http://www.scitools.org.uk/iris
    license: GNU Lesser General Public License
    summary: 'Units of measure as required by the Climate and Forecast (CF) metadata conventions.'