FROM centos:6

MAINTAINER ben.koziol@gmail.com

RUN yum -y update
RUN yum -y install wget \
                   tar \
                   bzip2 \
                   git \
                   gcc \
                   gcc-c++ \
                   gcc-gfortran \
                   which \
                   patch \
                   expat-devel \
                   libtool \
                   texinfo
RUN yum clean all

RUN wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
RUN bash miniconda.sh -b -p /opt/conda && rm miniconda.sh
RUN /opt/conda/bin/conda update --yes --all
RUN /opt/conda/bin/conda install --yes conda-build \
                                       anaconda-client
RUN rm -r /opt/conda/pkgs/*

ENV PATH /opt/conda/bin:$PATH
