package:
    name: ocgis
    version: 2.1.0.dev1

source:
    git_url: https://github.com/NCPP/ocgis.git
    git_tag: next

build:
    number: 2

requirements:
    build:
        - python
        - setuptools
        - fiona
        - gdal
        - netcdf4
        - shapely
        - pyproj
        - click
        - six
        - numpy

        # Needed for testing!
        - nose
        - mock
    run:
        - python
        - setuptools
        - fiona
        - gdal
        - netcdf4
        - shapely
        - pyproj
        - rtree
        - cf_units
        - click
        - six
        - numpy

#        - icclim ==4.2.9n #Optional!
#        - esmpy==7.0.0  #Optional!
#        - mpi4py  #Optional!

test:
  imports:
    - ocgis

about:
    home: http://ocgis.readthedocs.io
    license: NCSA License
    summary: OpenClimateGIS (OCGIS) is a set of geoprocessing and calculation tools for spatiotemporal datasets.
